# Generated by Django 5.2.7 on 2026-01-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthmix', '0002_announcementmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
