# Generated by Django 5.2.7 on 2026-01-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthmix', '0005_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Product',
            new_name='product',
        ),
    ]
