# Generated by Django 5.2.7 on 2026-02-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthmix', '0006_rename_product_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='address',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='address_line_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
