# Generated by Django 5.2.7 on 2026-02-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthmix', '0007_remove_useraddress_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
