# Generated by Django 5.2.7 on 2026-02-26 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthmix', '0008_alter_useraddress_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='weight_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthmix.productvariation'),
        ),
    ]
