# Generated by Django 5.2.7 on 2026-02-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthmix', '0009_alter_order_weight_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
